### ISSUE TITLE
User friendly navigation and responsive design for all pages

### ISSUE THREAD

**Issue by CristianaDvD** [CristianaDvD/but-first-bellydance#1]
**User story**
As a first time user I need to be able to identify easy all sections and navigate across all pages, so I can get information about what the website offers.

**Acceptance criteria**

- [x] The website is fully responsive on various screen sizes and different devices.
- [x] All pages can be easily seen and accessed.

**Tasks**

- [x] Use Bootstrap to ensure website is responsive across all devices and screen sizes.
- [x] Arrange navigation and pages section to be intuitive and easily accessed.
