### ISSUE TITLE
Classes options page

### ISSUE THREAD

**Issue by CristianaDvD** [CristianaDvD/but-first-bellydance#5]
**User story**
As a first time user I need to see what option would suit me best.
As a returning user I need to know what classes option I can refer further, or if I can change.

**Acceptance criteria**

- [x] Classes options by age 
- [x] Classes for adults depending on experience.

**Tasks**

- [x] Create section with different classes option for children by age group.
- [x] Create section with classes for adults by experience.
