### ISSUE TITLE
Join now modal form

### ISSUE THREAD

**Issue by CristianaDvD** [CristianaDvD/but-first-bellydance#6]
**User story**
As a new user I want to be able to access classes and send my details in order to start learning some moves.

**Acceptance criteria**

- [x] Join now button
- [x] Form with classes option, name, email address, phone number, age, date available to start.
- [ ] Parent details and consent required for children classes.

**Tasks**

- [x] Create modal form using Bootstrap, with all information required for name, age, email address, phone number, date.
- [ ] Create modal form for children classes to join and include parent details and consent required.
